name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install node v20
        uses: actions/setup-node@v2
        with:
            node:version: '20'
      - name: Install dependencies
        run: npm install
